/* ---------------------------------------------------------------
   The icon library.

   Slot, activity, counter, rule, achievement and reward icons are all chosen
   by name from this list and drawn through `RenderIcon`. Fixed UI chrome
   imports from `lucide-react` directly instead.

   Data, not components — keeping it out of `icons.tsx` is what lets that file
   stay fast-refreshable.

   **Grouped, and every entry carries search words.** The list is past three
   hundred now, which is well beyond what anybody scans: a grid that long is
   a haystack, and the group headings only narrow it to a dozen. So each entry
   says what its picture is *of*, in the words somebody would actually type —
   "gym" finds the dumbbell, "quit" finds the crossed-out cigarette — because
   the drawing and its export name agree far less often than you would hope.

   **The `name` strings are stored in saved data**, so entries can be added,
   regrouped and reworded freely, but never renamed and never removed.

   Generated — see `scratchpad/gen_icons.py` in the session that wrote it. The
   check that matters is not the generation but the two assertions it makes:
   every name is a real lucide export, and nothing already stored is dropped.
--------------------------------------------------------------- */

import type { LucideIcon } from "lucide-react"
import {
  Accessibility,
  Activity,
  AlarmClock,
  Ambulance,
  Anchor,
  Angry,
  Annoyed,
  Apple,
  Archive,
  Armchair,
  Atom,
  Award,
  Axe,
  Baby,
  Backpack,
  Ban,
  Banana,
  Bandage,
  Banknote,
  BarChart3,
  Bath,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bell,
  Bike,
  Binary,
  Binoculars,
  Bird,
  Blocks,
  Bone,
  BookA,
  BookCheck,
  BookHeart,
  BookMarked,
  BookOpen,
  BookX,
  Bookmark,
  Boxes,
  Brain,
  Briefcase,
  BrushCleaning,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  Caravan,
  Carrot,
  Castle,
  Cat,
  CheckSquare,
  Cherry,
  Church,
  Cigarette,
  CigaretteOff,
  Circle,
  CircleSlash,
  Citrus,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Code,
  Coffee,
  Coins,
  Compass,
  Contact,
  Container,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dices,
  Disc,
  Disc3,
  Divide,
  Dog,
  DoorOpen,
  Droplet,
  Drum,
  Dumbbell,
  Earth,
  Egg,
  Equal,
  Eye,
  EyeOff,
  Factory,
  Feather,
  Fence,
  FileCheck,
  FilePen,
  FileText,
  Files,
  Film,
  FingerprintPattern,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Frown,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Guitar,
  Hammer,
  Handshake,
  Hash,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Highlighter,
  Home,
  Hospital,
  Hotel,
  Hourglass,
  IceCreamCone,
  Image,
  Inbox,
  InfinityIcon,
  Joystick,
  Key,
  KeyRound,
  Keyboard,
  Lamp,
  LampDesk,
  Landmark,
  Languages,
  Laugh,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  ListChecks,
  ListMusic,
  Lock,
  LockOpen,
  Luggage,
  Mail,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  MessageCircleQuestion,
  MessageSquare,
  Mic,
  MicSignal,
  Microscope,
  Microwave,
  Milestone,
  Minus,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  Orbit,
  Origami,
  Package,
  PaintBucket,
  Paintbrush,
  Palette,
  Pause,
  PawPrint,
  PenLine,
  PenTool,
  Pencil,
  Percent,
  PersonStanding,
  Phone,
  Pi,
  Piano,
  Pickaxe,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Play,
  Plus,
  Popcorn,
  Presentation,
  Puzzle,
  QrCode,
  Rabbit,
  Radio,
  Rainbow,
  Receipt,
  Recycle,
  Redo2,
  RefreshCw,
  Refrigerator,
  Repeat,
  Repeat2,
  Rocket,
  RotateCcw,
  RotateCcwClock,
  Route,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  Scale,
  ScanFace,
  School,
  Scissors,
  ScrollText,
  Search,
  Shell,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Sigma,
  Signpost,
  Skull,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Sprout,
  Square,
  Squirrel,
  Stamp,
  Star,
  Stethoscope,
  Sticker,
  Store,
  Sun,
  SunMedium,
  Sunrise,
  Sunset,
  Superscript,
  Sword,
  Swords,
  Syringe,
  Tag,
  Tags,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  Thermometer,
  Ticket,
  Timer,
  Toilet,
  Train,
  TramFront,
  Trash2,
  TreePine,
  Trees,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  Undo2,
  UserCheck,
  UserPlus,
  Users,
  Utensils,
  Variable,
  Video,
  Volume2,
  Wallet,
  WandSparkles,
  Warehouse,
  WashingMachine,
  WavesHorizontal,
  Weight,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react"

export interface IconEntry {
  name: string
  icon: LucideIcon
  /** The heading it sits under in the picker. */
  group: string
  /** What the picture is of, for search. Not shown. */
  keywords: string
}

export const ICON_LIBRARY: IconEntry[] = [
  // Getting there
  { name: "Train", icon: Train, group: "Getting there", keywords: "rail metro subway" },
  { name: "Bus", icon: Bus, group: "Getting there", keywords: "coach" },
  { name: "Car", icon: Car, group: "Getting there", keywords: "drive auto" },
  { name: "Bike", icon: Bike, group: "Getting there", keywords: "cycle bicycle cycling" },
  { name: "Ship", icon: Ship, group: "Getting there", keywords: "boat sea" },
  { name: "Sailboat", icon: Sailboat, group: "Getting there", keywords: "yacht sailing" },
  { name: "Plane", icon: Plane, group: "Getting there", keywords: "flight fly airport travel" },
  { name: "TramFront", icon: TramFront, group: "Getting there", keywords: "tram streetcar" },
  { name: "Truck", icon: Truck, group: "Getting there", keywords: "lorry delivery" },
  { name: "Caravan", icon: Caravan, group: "Getting there", keywords: "camper motorhome" },
  { name: "Fuel", icon: Fuel, group: "Getting there", keywords: "petrol gas station" },
  { name: "Footprints", icon: Footprints, group: "Getting there", keywords: "walk walking steps" },
  { name: "MapPin", icon: MapPin, group: "Getting there", keywords: "location place" },
  { name: "Map", icon: Map, group: "Getting there", keywords: "atlas" },
  { name: "Route", icon: Route, group: "Getting there", keywords: "path journey" },
  { name: "Navigation", icon: Navigation, group: "Getting there", keywords: "direction gps" },
  { name: "Signpost", icon: Signpost, group: "Getting there", keywords: "direction sign" },
  { name: "Milestone", icon: Milestone, group: "Getting there", keywords: "marker" },
  { name: "Compass", icon: Compass, group: "Getting there", keywords: "direction bearing" },
  { name: "Anchor", icon: Anchor, group: "Getting there", keywords: "harbour port" },
  { name: "Luggage", icon: Luggage, group: "Getting there", keywords: "suitcase travel trip" },
  { name: "Backpack", icon: Backpack, group: "Getting there", keywords: "rucksack bag school" },
  { name: "Tent", icon: Tent, group: "Getting there", keywords: "camping outdoors" },
  { name: "Binoculars", icon: Binoculars, group: "Getting there", keywords: "watch spot birding" },

  // Times of day and weather
  { name: "Sunrise", icon: Sunrise, group: "Times of day and weather", keywords: "morning dawn early" },
  { name: "Sun", icon: Sun, group: "Times of day and weather", keywords: "day sunny noon" },
  { name: "SunMedium", icon: SunMedium, group: "Times of day and weather", keywords: "daylight bright" },
  { name: "Sunset", icon: Sunset, group: "Times of day and weather", keywords: "evening dusk" },
  { name: "Moon", icon: Moon, group: "Times of day and weather", keywords: "night sleep late" },
  { name: "MoonStar", icon: MoonStar, group: "Times of day and weather", keywords: "night clear" },
  { name: "Cloud", icon: Cloud, group: "Times of day and weather", keywords: "overcast" },
  { name: "CloudRain", icon: CloudRain, group: "Times of day and weather", keywords: "rain wet shower" },
  { name: "CloudSnow", icon: CloudSnow, group: "Times of day and weather", keywords: "snow winter" },
  { name: "CloudLightning", icon: CloudLightning, group: "Times of day and weather", keywords: "storm thunder" },
  { name: "Wind", icon: Wind, group: "Times of day and weather", keywords: "windy breeze" },
  { name: "Rainbow", icon: Rainbow, group: "Times of day and weather", keywords: "colour" },
  { name: "Umbrella", icon: Umbrella, group: "Times of day and weather", keywords: "rain shelter" },
  { name: "Snowflake", icon: Snowflake, group: "Times of day and weather", keywords: "freeze winter cold" },
  { name: "Droplet", icon: Droplet, group: "Times of day and weather", keywords: "water rain drop" },
  { name: "Flame", icon: Flame, group: "Times of day and weather", keywords: "fire burn streak hot" },
  { name: "Earth", icon: Earth, group: "Times of day and weather", keywords: "world planet globe" },
  { name: "Orbit", icon: Orbit, group: "Times of day and weather", keywords: "planet space" },
  { name: "Satellite", icon: Satellite, group: "Times of day and weather", keywords: "space signal" },
  { name: "Telescope", icon: Telescope, group: "Times of day and weather", keywords: "stars astronomy space" },

  // The clock
  { name: "Clock", icon: Clock, group: "The clock", keywords: "time hour watch" },
  { name: "AlarmClock", icon: AlarmClock, group: "The clock", keywords: "alarm wake morning" },
  { name: "Timer", icon: Timer, group: "The clock", keywords: "countdown stopwatch" },
  { name: "Hourglass", icon: Hourglass, group: "The clock", keywords: "waiting sand time" },
  { name: "CalendarDays", icon: CalendarDays, group: "The clock", keywords: "date month schedule" },
  { name: "Bell", icon: Bell, group: "The clock", keywords: "reminder notification alert" },
  { name: "RotateCcwClock", icon: RotateCcwClock, group: "The clock", keywords: "history past log" },
  { name: "Repeat", icon: Repeat, group: "The clock", keywords: "again loop routine" },
  { name: "Repeat2", icon: Repeat2, group: "The clock", keywords: "loop cycle" },
  { name: "RefreshCw", icon: RefreshCw, group: "The clock", keywords: "refresh reset again" },
  { name: "RotateCcw", icon: RotateCcw, group: "The clock", keywords: "undo back reset" },
  { name: "Undo2", icon: Undo2, group: "The clock", keywords: "back revert" },
  { name: "Redo2", icon: Redo2, group: "The clock", keywords: "forward again" },
  { name: "Play", icon: Play, group: "The clock", keywords: "start begin go" },
  { name: "Pause", icon: Pause, group: "The clock", keywords: "break stop rest" },
  { name: "Square", icon: Square, group: "The clock", keywords: "stop end" },
  { name: "Circle", icon: Circle, group: "The clock", keywords: "dot round" },

  // Studying
  { name: "BookOpen", icon: BookOpen, group: "Studying", keywords: "read reading study lesson" },
  { name: "BookMarked", icon: BookMarked, group: "Studying", keywords: "read reference" },
  { name: "BookA", icon: BookA, group: "Studying", keywords: "dictionary vocabulary language" },
  { name: "BookCheck", icon: BookCheck, group: "Studying", keywords: "finished read done" },
  { name: "BookHeart", icon: BookHeart, group: "Studying", keywords: "favourite read" },
  { name: "BookX", icon: BookX, group: "Studying", keywords: "dropped abandoned" },
  { name: "Library", icon: Library, group: "Studying", keywords: "books shelf" },
  { name: "School", icon: School, group: "Studying", keywords: "class lesson" },
  { name: "GraduationCap", icon: GraduationCap, group: "Studying", keywords: "exam degree graduate university" },
  { name: "Notebook", icon: Notebook, group: "Studying", keywords: "notes journal" },
  { name: "NotebookPen", icon: NotebookPen, group: "Studying", keywords: "notes writing journal" },
  { name: "NotebookText", icon: NotebookText, group: "Studying", keywords: "notes lined" },
  { name: "NotebookTabs", icon: NotebookTabs, group: "Studying", keywords: "notes sections" },
  { name: "ScrollText", icon: ScrollText, group: "Studying", keywords: "essay text long" },
  { name: "FileText", icon: FileText, group: "Studying", keywords: "document paper" },
  { name: "FileCheck", icon: FileCheck, group: "Studying", keywords: "done marked" },
  { name: "FilePen", icon: FilePen, group: "Studying", keywords: "draft editing" },
  { name: "Files", icon: Files, group: "Studying", keywords: "documents papers" },
  { name: "Archive", icon: Archive, group: "Studying", keywords: "stored old box" },
  { name: "Inbox", icon: Inbox, group: "Studying", keywords: "incoming tray" },
  { name: "Newspaper", icon: Newspaper, group: "Studying", keywords: "news article" },
  { name: "ClipboardList", icon: ClipboardList, group: "Studying", keywords: "checklist tasks" },
  { name: "Presentation", icon: Presentation, group: "Studying", keywords: "slides talk lecture" },
  { name: "Languages", icon: Languages, group: "Studying", keywords: "translate foreign" },
  { name: "PenLine", icon: PenLine, group: "Studying", keywords: "write writing" },
  { name: "Pencil", icon: Pencil, group: "Studying", keywords: "write edit draft" },
  { name: "Highlighter", icon: Highlighter, group: "Studying", keywords: "mark revise" },
  { name: "Ruler", icon: Ruler, group: "Studying", keywords: "measure straight" },
  { name: "Calculator", icon: Calculator, group: "Studying", keywords: "maths arithmetic sums" },

  // Thinking and asking
  { name: "Brain", icon: Brain, group: "Thinking and asking", keywords: "think memory mind" },
  { name: "Lightbulb", icon: Lightbulb, group: "Thinking and asking", keywords: "idea insight" },
  { name: "MessageCircleQuestion", icon: MessageCircleQuestion, group: "Thinking and asking", keywords: "question ask qa" },
  { name: "HelpCircle", icon: HelpCircle, group: "Thinking and asking", keywords: "question help unsure" },
  { name: "Puzzle", icon: Puzzle, group: "Thinking and asking", keywords: "problem piece solve" },
  { name: "Search", icon: Search, group: "Thinking and asking", keywords: "find look lookup" },
  { name: "Microscope", icon: Microscope, group: "Thinking and asking", keywords: "research detail study" },
  { name: "FlaskConical", icon: FlaskConical, group: "Thinking and asking", keywords: "experiment lab chemistry" },
  { name: "Atom", icon: Atom, group: "Thinking and asking", keywords: "physics science" },
  { name: "Sigma", icon: Sigma, group: "Thinking and asking", keywords: "sum maths total" },
  { name: "Pi", icon: Pi, group: "Thinking and asking", keywords: "maths constant" },
  { name: "Infinity", icon: InfinityIcon, group: "Thinking and asking", keywords: "endless forever" },
  { name: "Variable", icon: Variable, group: "Thinking and asking", keywords: "algebra unknown" },
  { name: "Divide", icon: Divide, group: "Thinking and asking", keywords: "maths division" },
  { name: "Equal", icon: Equal, group: "Thinking and asking", keywords: "maths same" },
  { name: "Percent", icon: Percent, group: "Thinking and asking", keywords: "percentage share" },
  { name: "Superscript", icon: Superscript, group: "Thinking and asking", keywords: "power exponent" },

  // Building things
  { name: "Code", icon: Code, group: "Building things", keywords: "programming dev software" },
  { name: "Terminal", icon: Terminal, group: "Building things", keywords: "shell console command" },
  { name: "Database", icon: Database, group: "Building things", keywords: "data sql storage" },
  { name: "GitBranch", icon: GitBranch, group: "Building things", keywords: "git version branch" },
  { name: "Bug", icon: Bug, group: "Building things", keywords: "fix defect debug" },
  { name: "Binary", icon: Binary, group: "Building things", keywords: "bits computing" },
  { name: "Cpu", icon: Cpu, group: "Building things", keywords: "processor hardware" },
  { name: "Keyboard", icon: Keyboard, group: "Building things", keywords: "typing type" },
  { name: "Monitor", icon: Monitor, group: "Building things", keywords: "screen desktop computer" },
  { name: "Globe", icon: Globe, group: "Building things", keywords: "web internet world" },
  { name: "Wrench", icon: Wrench, group: "Building things", keywords: "fix tool repair" },
  { name: "Hammer", icon: Hammer, group: "Building things", keywords: "build tool diy" },
  { name: "Axe", icon: Axe, group: "Building things", keywords: "chop tool wood" },
  { name: "Shovel", icon: Shovel, group: "Building things", keywords: "dig garden tool" },
  { name: "Pickaxe", icon: Pickaxe, group: "Building things", keywords: "mine dig tool" },
  { name: "Scissors", icon: Scissors, group: "Building things", keywords: "cut craft" },
  { name: "PenTool", icon: PenTool, group: "Building things", keywords: "vector design draw" },
  { name: "Paintbrush", icon: Paintbrush, group: "Building things", keywords: "paint art" },
  { name: "PaintBucket", icon: PaintBucket, group: "Building things", keywords: "fill colour paint" },
  { name: "Stamp", icon: Stamp, group: "Building things", keywords: "approve mark" },
  { name: "Sticker", icon: Sticker, group: "Building things", keywords: "label badge" },
  { name: "Origami", icon: Origami, group: "Building things", keywords: "paper fold craft" },
  { name: "Blocks", icon: Blocks, group: "Building things", keywords: "build lego pieces" },
  { name: "Boxes", icon: Boxes, group: "Building things", keywords: "stock things many" },
  { name: "Container", icon: Container, group: "Building things", keywords: "shipping box" },
  { name: "Layers", icon: Layers, group: "Building things", keywords: "stack levels" },
  { name: "Package", icon: Package, group: "Building things", keywords: "box parcel delivery" },
  { name: "Folder", icon: Folder, group: "Building things", keywords: "files directory" },

  // Lists and progress
  { name: "ListChecks", icon: ListChecks, group: "Lists and progress", keywords: "todo checklist tasks" },
  { name: "CheckSquare", icon: CheckSquare, group: "Lists and progress", keywords: "done tick complete" },
  { name: "Target", icon: Target, group: "Lists and progress", keywords: "goal aim objective" },
  { name: "Flag", icon: Flag, group: "Lists and progress", keywords: "milestone mark finish" },
  { name: "Bookmark", icon: Bookmark, group: "Lists and progress", keywords: "save mark later" },
  { name: "Tag", icon: Tag, group: "Lists and progress", keywords: "label category" },
  { name: "Gauge", icon: Gauge, group: "Lists and progress", keywords: "meter level speed" },
  { name: "TrendingUp", icon: TrendingUp, group: "Lists and progress", keywords: "growth rising better" },
  { name: "BarChart3", icon: BarChart3, group: "Lists and progress", keywords: "chart stats bars" },
  { name: "LineChart", icon: LineChart, group: "Lists and progress", keywords: "chart trend graph" },
  { name: "PieChart", icon: PieChart, group: "Lists and progress", keywords: "chart share split" },
  { name: "Activity", icon: Activity, group: "Lists and progress", keywords: "pulse heartbeat trend" },
  { name: "Scale", icon: Scale, group: "Lists and progress", keywords: "balance weigh fair" },
  { name: "Weight", icon: Weight, group: "Lists and progress", keywords: "kg heavy lifting" },
  { name: "Plus", icon: Plus, group: "Lists and progress", keywords: "add more increase" },
  { name: "Minus", icon: Minus, group: "Lists and progress", keywords: "less remove decrease" },
  { name: "Hash", icon: Hash, group: "Lists and progress", keywords: "number count tag" },

  // Rewards
  { name: "Trophy", icon: Trophy, group: "Rewards", keywords: "win prize champion achievement reward" },
  { name: "Medal", icon: Medal, group: "Rewards", keywords: "prize award place reward" },
  { name: "Award", icon: Award, group: "Rewards", keywords: "prize ribbon reward" },
  { name: "Crown", icon: Crown, group: "Rewards", keywords: "king best top" },
  { name: "Star", icon: Star, group: "Rewards", keywords: "favourite rating best reward" },
  { name: "Sparkles", icon: Sparkles, group: "Rewards", keywords: "magic special new" },
  { name: "Sparkle", icon: Sparkle, group: "Rewards", keywords: "shine special" },
  { name: "WandSparkles", icon: WandSparkles, group: "Rewards", keywords: "magic wish" },
  { name: "Gem", icon: Gem, group: "Rewards", keywords: "jewel precious rare reward" },
  { name: "Diamond", icon: Diamond, group: "Rewards", keywords: "precious rare" },
  { name: "Zap", icon: Zap, group: "Rewards", keywords: "energy fast power" },
  { name: "Rocket", icon: Rocket, group: "Rewards", keywords: "launch fast ambition" },
  { name: "Gift", icon: Gift, group: "Rewards", keywords: "present reward treat" },
  { name: "ShoppingBag", icon: ShoppingBag, group: "Rewards", keywords: "buy shop purchase" },
  { name: "ShoppingCart", icon: ShoppingCart, group: "Rewards", keywords: "buy basket shop" },
  { name: "Ticket", icon: Ticket, group: "Rewards", keywords: "entry cinema event" },
  { name: "CreditCard", icon: CreditCard, group: "Rewards", keywords: "pay card money" },
  { name: "Banknote", icon: Banknote, group: "Rewards", keywords: "money cash note" },
  { name: "Coins", icon: Coins, group: "Rewards", keywords: "money coins savings" },
  { name: "PiggyBank", icon: PiggyBank, group: "Rewards", keywords: "savings save money" },
  { name: "Receipt", icon: Receipt, group: "Rewards", keywords: "bill purchase record" },
  { name: "Tags", icon: Tags, group: "Rewards", keywords: "labels price" },

  // Food and drink
  { name: "Coffee", icon: Coffee, group: "Food and drink", keywords: "caffeine drink break morning" },
  { name: "CupSoda", icon: CupSoda, group: "Food and drink", keywords: "drink soft cold" },
  { name: "Beer", icon: Beer, group: "Food and drink", keywords: "pub alcohol drink" },
  { name: "Wine", icon: Wine, group: "Food and drink", keywords: "alcohol drink glass" },
  { name: "Martini", icon: Martini, group: "Food and drink", keywords: "cocktail alcohol drink" },
  { name: "Cake", icon: Cake, group: "Food and drink", keywords: "birthday dessert treat" },
  { name: "Cookie", icon: Cookie, group: "Food and drink", keywords: "biscuit treat snack" },
  { name: "Croissant", icon: Croissant, group: "Food and drink", keywords: "pastry breakfast" },
  { name: "IceCreamCone", icon: IceCreamCone, group: "Food and drink", keywords: "dessert cold treat" },
  { name: "Pizza", icon: Pizza, group: "Food and drink", keywords: "takeaway dinner treat" },
  { name: "Sandwich", icon: Sandwich, group: "Food and drink", keywords: "lunch food" },
  { name: "Popcorn", icon: Popcorn, group: "Food and drink", keywords: "cinema snack film" },
  { name: "Salad", icon: Salad, group: "Food and drink", keywords: "healthy greens lunch" },
  { name: "Soup", icon: Soup, group: "Food and drink", keywords: "hot bowl food" },
  { name: "Beef", icon: Beef, group: "Food and drink", keywords: "meat dinner" },
  { name: "Fish", icon: Fish, group: "Food and drink", keywords: "seafood dinner" },
  { name: "Egg", icon: Egg, group: "Food and drink", keywords: "breakfast protein" },
  { name: "Carrot", icon: Carrot, group: "Food and drink", keywords: "vegetable healthy" },
  { name: "Cherry", icon: Cherry, group: "Food and drink", keywords: "fruit" },
  { name: "Grape", icon: Grape, group: "Food and drink", keywords: "fruit" },
  { name: "Citrus", icon: Citrus, group: "Food and drink", keywords: "orange lemon fruit" },
  { name: "Banana", icon: Banana, group: "Food and drink", keywords: "fruit" },
  { name: "Apple", icon: Apple, group: "Food and drink", keywords: "fruit healthy" },
  { name: "Utensils", icon: Utensils, group: "Food and drink", keywords: "eat meal dinner restaurant" },

  // Making and listening
  { name: "Music", icon: Music, group: "Making and listening", keywords: "song audio tune" },
  { name: "Headphones", icon: Headphones, group: "Making and listening", keywords: "listen audio music" },
  { name: "Speaker", icon: Speaker, group: "Making and listening", keywords: "sound audio loud" },
  { name: "Volume2", icon: Volume2, group: "Making and listening", keywords: "sound loud audio" },
  { name: "ListMusic", icon: ListMusic, group: "Making and listening", keywords: "playlist songs" },
  { name: "Disc", icon: Disc, group: "Making and listening", keywords: "album cd record" },
  { name: "Disc3", icon: Disc3, group: "Making and listening", keywords: "vinyl record album" },
  { name: "Guitar", icon: Guitar, group: "Making and listening", keywords: "instrument play music" },
  { name: "Piano", icon: Piano, group: "Making and listening", keywords: "instrument keys music" },
  { name: "Drum", icon: Drum, group: "Making and listening", keywords: "instrument percussion" },
  { name: "Mic", icon: Mic, group: "Making and listening", keywords: "record voice sing" },
  { name: "MicSignal", icon: MicSignal, group: "Making and listening", keywords: "podcast broadcast" },
  { name: "Radio", icon: Radio, group: "Making and listening", keywords: "broadcast station" },
  { name: "Tv", icon: Tv, group: "Making and listening", keywords: "television watch show" },
  { name: "Video", icon: Video, group: "Making and listening", keywords: "film record watch" },
  { name: "Film", icon: Film, group: "Making and listening", keywords: "movie cinema" },
  { name: "Clapperboard", icon: Clapperboard, group: "Making and listening", keywords: "film shoot scene" },
  { name: "Camera", icon: Camera, group: "Making and listening", keywords: "photo picture" },
  { name: "Image", icon: Image, group: "Making and listening", keywords: "picture photo" },
  { name: "Palette", icon: Palette, group: "Making and listening", keywords: "art colour paint draw" },
  { name: "Gamepad2", icon: Gamepad2, group: "Making and listening", keywords: "game play console" },
  { name: "Joystick", icon: Joystick, group: "Making and listening", keywords: "game arcade play" },
  { name: "Dices", icon: Dices, group: "Making and listening", keywords: "game chance random" },
  { name: "Swords", icon: Swords, group: "Making and listening", keywords: "fight duel game" },
  { name: "Sword", icon: Sword, group: "Making and listening", keywords: "blade fight" },
  { name: "Castle", icon: Castle, group: "Making and listening", keywords: "fortress game" },

  // Body and rest
  { name: "Dumbbell", icon: Dumbbell, group: "Body and rest", keywords: "gym weights workout exercise lifting" },
  { name: "HeartPulse", icon: HeartPulse, group: "Body and rest", keywords: "health fitness cardio" },
  { name: "Heart", icon: Heart, group: "Body and rest", keywords: "love like favourite" },
  { name: "HeartHandshake", icon: HeartHandshake, group: "Body and rest", keywords: "care support kindness" },
  { name: "PersonStanding", icon: PersonStanding, group: "Body and rest", keywords: "person body posture" },
  { name: "Accessibility", icon: Accessibility, group: "Body and rest", keywords: "access ability" },
  { name: "Bed", icon: Bed, group: "Body and rest", keywords: "sleep rest night" },
  { name: "BedDouble", icon: BedDouble, group: "Body and rest", keywords: "sleep bedroom" },
  { name: "Bath", icon: Bath, group: "Body and rest", keywords: "wash relax soak" },
  { name: "ShowerHead", icon: ShowerHead, group: "Body and rest", keywords: "wash shower morning" },
  { name: "Stethoscope", icon: Stethoscope, group: "Body and rest", keywords: "doctor health checkup" },
  { name: "Pill", icon: Pill, group: "Body and rest", keywords: "medicine tablet" },
  { name: "Syringe", icon: Syringe, group: "Body and rest", keywords: "injection vaccine" },
  { name: "Bandage", icon: Bandage, group: "Body and rest", keywords: "injury plaster" },
  { name: "Thermometer", icon: Thermometer, group: "Body and rest", keywords: "fever temperature" },
  { name: "Cross", icon: Cross, group: "Body and rest", keywords: "medical aid health" },
  { name: "Ambulance", icon: Ambulance, group: "Body and rest", keywords: "emergency hospital" },
  { name: "Smile", icon: Smile, group: "Body and rest", keywords: "happy mood good" },
  { name: "Laugh", icon: Laugh, group: "Body and rest", keywords: "happy funny" },
  { name: "Meh", icon: Meh, group: "Body and rest", keywords: "neutral mood ok" },
  { name: "Frown", icon: Frown, group: "Body and rest", keywords: "sad mood bad" },
  { name: "Annoyed", icon: Annoyed, group: "Body and rest", keywords: "irritated mood" },
  { name: "Angry", icon: Angry, group: "Body and rest", keywords: "mad mood cross" },

  // Home
  { name: "Home", icon: Home, group: "Home", keywords: "house flat" },
  { name: "Sofa", icon: Sofa, group: "Home", keywords: "living room lounge" },
  { name: "Armchair", icon: Armchair, group: "Home", keywords: "chair sit relax" },
  { name: "Lamp", icon: Lamp, group: "Home", keywords: "light room" },
  { name: "LampDesk", icon: LampDesk, group: "Home", keywords: "desk light work" },
  { name: "DoorOpen", icon: DoorOpen, group: "Home", keywords: "leave enter door" },
  { name: "Refrigerator", icon: Refrigerator, group: "Home", keywords: "fridge kitchen" },
  { name: "Microwave", icon: Microwave, group: "Home", keywords: "kitchen cook" },
  { name: "WashingMachine", icon: WashingMachine, group: "Home", keywords: "laundry chores" },
  { name: "Toilet", icon: Toilet, group: "Home", keywords: "bathroom" },
  { name: "BrushCleaning", icon: BrushCleaning, group: "Home", keywords: "clean chores tidy" },
  { name: "Trash2", icon: Trash2, group: "Home", keywords: "bin rubbish delete" },
  { name: "Recycle", icon: Recycle, group: "Home", keywords: "reuse green waste" },
  { name: "Fence", icon: Fence, group: "Home", keywords: "garden boundary" },

  // Nature and animals
  { name: "Leaf", icon: Leaf, group: "Nature and animals", keywords: "plant green nature" },
  { name: "Sprout", icon: Sprout, group: "Nature and animals", keywords: "grow seedling start" },
  { name: "Flower", icon: Flower, group: "Nature and animals", keywords: "bloom garden" },
  { name: "Flower2", icon: Flower2, group: "Nature and animals", keywords: "bloom petal" },
  { name: "TreePine", icon: TreePine, group: "Nature and animals", keywords: "tree forest nature" },
  { name: "Trees", icon: Trees, group: "Nature and animals", keywords: "forest woods" },
  { name: "TentTree", icon: TentTree, group: "Nature and animals", keywords: "camping forest outdoors" },
  { name: "Mountain", icon: Mountain, group: "Nature and animals", keywords: "hill climb peak" },
  { name: "MountainSnow", icon: MountainSnow, group: "Nature and animals", keywords: "alps peak winter" },
  { name: "WavesHorizontal", icon: WavesHorizontal, group: "Nature and animals", keywords: "sea water swim" },
  { name: "Feather", icon: Feather, group: "Nature and animals", keywords: "light quill bird" },
  { name: "Bird", icon: Bird, group: "Nature and animals", keywords: "animal fly" },
  { name: "Cat", icon: Cat, group: "Nature and animals", keywords: "animal pet" },
  { name: "Dog", icon: Dog, group: "Nature and animals", keywords: "animal pet walk" },
  { name: "Rabbit", icon: Rabbit, group: "Nature and animals", keywords: "animal pet fast" },
  { name: "Squirrel", icon: Squirrel, group: "Nature and animals", keywords: "animal" },
  { name: "Turtle", icon: Turtle, group: "Nature and animals", keywords: "animal slow" },
  { name: "PawPrint", icon: PawPrint, group: "Nature and animals", keywords: "animal pet" },
  { name: "Shell", icon: Shell, group: "Nature and animals", keywords: "sea beach" },
  { name: "Bone", icon: Bone, group: "Nature and animals", keywords: "dog skeleton" },

  // Places and people
  { name: "Building2", icon: Building2, group: "Places and people", keywords: "office block city" },
  { name: "Building", icon: Building, group: "Places and people", keywords: "office block" },
  { name: "Store", icon: Store, group: "Places and people", keywords: "shop retail" },
  { name: "Landmark", icon: Landmark, group: "Places and people", keywords: "bank museum civic" },
  { name: "Church", icon: Church, group: "Places and people", keywords: "chapel religion" },
  { name: "Hotel", icon: Hotel, group: "Places and people", keywords: "stay travel" },
  { name: "Hospital", icon: Hospital, group: "Places and people", keywords: "medical care" },
  { name: "Factory", icon: Factory, group: "Places and people", keywords: "industry work" },
  { name: "Warehouse", icon: Warehouse, group: "Places and people", keywords: "storage depot" },
  { name: "Briefcase", icon: Briefcase, group: "Places and people", keywords: "work job business" },
  { name: "Users", icon: Users, group: "Places and people", keywords: "people group team" },
  { name: "UserCheck", icon: UserCheck, group: "Places and people", keywords: "approved member" },
  { name: "UserPlus", icon: UserPlus, group: "Places and people", keywords: "invite add person" },
  { name: "Contact", icon: Contact, group: "Places and people", keywords: "person card details" },
  { name: "Handshake", icon: Handshake, group: "Places and people", keywords: "deal agree partner" },
  { name: "Baby", icon: Baby, group: "Places and people", keywords: "child infant family" },
  { name: "MessageSquare", icon: MessageSquare, group: "Places and people", keywords: "chat message talk" },
  { name: "Mail", icon: Mail, group: "Places and people", keywords: "email letter post" },
  { name: "Phone", icon: Phone, group: "Places and people", keywords: "call ring mobile" },
  { name: "Wallet", icon: Wallet, group: "Places and people", keywords: "money purse cash" },

  // Warnings and limits
  { name: "Ban", icon: Ban, group: "Warnings and limits", keywords: "no forbidden stop quit" },
  { name: "CircleSlash", icon: CircleSlash, group: "Warnings and limits", keywords: "none zero forbidden" },
  { name: "Cigarette", icon: Cigarette, group: "Warnings and limits", keywords: "smoking vice" },
  { name: "CigaretteOff", icon: CigaretteOff, group: "Warnings and limits", keywords: "quit smoking stopped" },
  { name: "Skull", icon: Skull, group: "Warnings and limits", keywords: "danger death poison" },
  { name: "TriangleAlert", icon: TriangleAlert, group: "Warnings and limits", keywords: "warning careful risk" },
  { name: "ShieldAlert", icon: ShieldAlert, group: "Warnings and limits", keywords: "risk protect warning" },
  { name: "ShieldCheck", icon: ShieldCheck, group: "Warnings and limits", keywords: "safe protected verified" },
  { name: "ShieldHalf", icon: ShieldHalf, group: "Warnings and limits", keywords: "partly protected" },
  { name: "Shield", icon: Shield, group: "Warnings and limits", keywords: "protect guard safe" },
  { name: "Eye", icon: Eye, group: "Warnings and limits", keywords: "watch see visible" },
  { name: "EyeOff", icon: EyeOff, group: "Warnings and limits", keywords: "hidden unseen ignore" },
  { name: "Glasses", icon: Glasses, group: "Warnings and limits", keywords: "read sight vision" },
  { name: "Lock", icon: Lock, group: "Warnings and limits", keywords: "locked secure private" },
  { name: "LockOpen", icon: LockOpen, group: "Warnings and limits", keywords: "unlocked open free" },
  { name: "Key", icon: Key, group: "Warnings and limits", keywords: "access unlock" },
  { name: "KeyRound", icon: KeyRound, group: "Warnings and limits", keywords: "access unlock key" },
  { name: "ScanFace", icon: ScanFace, group: "Warnings and limits", keywords: "identity face login" },
  { name: "FingerprintPattern", icon: FingerprintPattern, group: "Warnings and limits", keywords: "identity print login" },
  { name: "QrCode", icon: QrCode, group: "Warnings and limits", keywords: "scan code" },
]

export const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map((o) => [o.name, o.icon]),
)

export const FALLBACK_ICON = HelpCircle

/** The group headings, in the order the picker should draw them. */
export const ICON_GROUPS: string[] = [
  "Getting there",
  "Times of day and weather",
  "The clock",
  "Studying",
  "Thinking and asking",
  "Building things",
  "Lists and progress",
  "Rewards",
  "Food and drink",
  "Making and listening",
  "Body and rest",
  "Home",
  "Nature and animals",
  "Places and people",
  "Warnings and limits",
]

/**
 * Does this icon answer that search?
 *
 * The name is matched with its capitals split apart, so "clock" finds
 * `AlarmClock` and "check" finds `ShieldCheck` — otherwise half the library is
 * unreachable by the word a person would type for it.
 */
export function iconMatches(entry: IconEntry, query: string): boolean {
  const q = query.trim().toLowerCase()
  if (!q) return true
  // The group is deliberately **not** searched. It reads like a free win and
  // is not: "clock" would drag in Play, Pause and Circle because they happen
  // to be filed under The clock, and a search that answers with its whole
  // shelf is worse than one that answers with nothing. The headings already
  // do that job, and they do it while you are browsing, which is when it is
  // wanted. A word worth finding a group by belongs in its entries' keywords.
  const haystack = `${entry.name.replace(/([a-z])([A-Z0-9])/g, "$1 $2")} ${
    entry.keywords
  }`.toLowerCase()
  return q.split(/\s+/).every((word) => haystack.includes(word))
}
