/* ---------------------------------------------------------------
   The icon library.

   Slot and category icons are user-configurable, so they are chosen by name
   from this list and drawn through `RenderIcon`. Fixed UI chrome imports from
   `lucide-react` directly instead.

   Data, not components — keeping it out of `icons.tsx` is what lets that file
   stay fast-refreshable.

   Grouped by theme rather than alphabetically: the picker is a grid you scan,
   and a run of related icons is far quicker to search than an A–Z list where
   the thing you want could be anywhere. **The `name` strings are stored in
   saved data**, so they can be added and reordered freely but never renamed.
--------------------------------------------------------------- */

import type { LucideIcon } from "lucide-react"
import {
  Activity,
  AlarmClock,
  Anchor,
  Apple,
  Atom,
  Award,
  BarChart3,
  Bed,
  Bell,
  Bike,
  Binary,
  BookMarked,
  BookOpen,
  Bookmark,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Bus,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  CheckSquare,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  Crown,
  Database,
  Droplet,
  Dumbbell,
  Feather,
  FileText,
  Film,
  FlaskConical,
  Flag,
  Flame,
  Folder,
  Footprints,
  Gamepad2,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Highlighter,
  Home,
  Hourglass,
  Image,
  Key,
  Keyboard,
  Languages,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircleQuestion,
  MessageSquare,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Music,
  NotebookPen,
  Package,
  Palette,
  Pencil,
  PenLine,
  Percent,
  Phone,
  PieChart,
  Presentation,
  Puzzle,
  Rocket,
  Ruler,
  School,
  ScrollText,
  Search,
  Shield,
  Ship,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Target,
  Terminal,
  Timer,
  Train,
  TreePine,
  TrendingUp,
  Trophy,
  Users,
  Utensils,
  Video,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react"

export interface IconEntry {
  name: string
  icon: LucideIcon
}

export const ICON_LIBRARY: IconEntry[] = [
  // Getting there
  { name: "Train", icon: Train },
  { name: "Bus", icon: Bus },
  { name: "Car", icon: Car },
  { name: "Bike", icon: Bike },
  { name: "Ship", icon: Ship },
  { name: "Footprints", icon: Footprints },
  { name: "MapPin", icon: MapPin },
  { name: "Map", icon: Map },
  { name: "Compass", icon: Compass },
  { name: "Anchor", icon: Anchor },

  // Times of day and weather
  { name: "Sunrise", icon: Sunrise },
  { name: "Sun", icon: Sun },
  { name: "Sunset", icon: Sunset },
  { name: "Moon", icon: Moon },
  { name: "Cloud", icon: Cloud },
  { name: "Snowflake", icon: Snowflake },
  { name: "Droplet", icon: Droplet },
  { name: "Flame", icon: Flame },

  // The clock
  { name: "Clock", icon: Clock },
  { name: "AlarmClock", icon: AlarmClock },
  { name: "Timer", icon: Timer },
  { name: "Hourglass", icon: Hourglass },
  { name: "CalendarDays", icon: CalendarDays },
  { name: "Bell", icon: Bell },

  // Studying
  { name: "BookOpen", icon: BookOpen },
  { name: "BookMarked", icon: BookMarked },
  { name: "Library", icon: Library },
  { name: "School", icon: School },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "NotebookPen", icon: NotebookPen },
  { name: "ScrollText", icon: ScrollText },
  { name: "FileText", icon: FileText },
  { name: "ClipboardList", icon: ClipboardList },
  { name: "Presentation", icon: Presentation },
  { name: "Languages", icon: Languages },
  { name: "PenLine", icon: PenLine },
  { name: "Pencil", icon: Pencil },
  { name: "Highlighter", icon: Highlighter },
  { name: "Ruler", icon: Ruler },
  { name: "Calculator", icon: Calculator },

  // Thinking and asking
  { name: "Brain", icon: Brain },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "MessageCircleQuestion", icon: MessageCircleQuestion },
  { name: "HelpCircle", icon: HelpCircle },
  { name: "Puzzle", icon: Puzzle },
  { name: "Search", icon: Search },
  { name: "Microscope", icon: Microscope },
  { name: "FlaskConical", icon: FlaskConical },
  { name: "Atom", icon: Atom },

  // Building things
  { name: "Code", icon: Code },
  { name: "Terminal", icon: Terminal },
  { name: "Database", icon: Database },
  { name: "GitBranch", icon: GitBranch },
  { name: "Bug", icon: Bug },
  { name: "Binary", icon: Binary },
  { name: "Cpu", icon: Cpu },
  { name: "Keyboard", icon: Keyboard },
  { name: "Monitor", icon: Monitor },
  { name: "Globe", icon: Globe },
  { name: "Wrench", icon: Wrench },
  { name: "Layers", icon: Layers },
  { name: "Package", icon: Package },
  { name: "Folder", icon: Folder },

  // Lists and progress
  { name: "ListChecks", icon: ListChecks },
  { name: "CheckSquare", icon: CheckSquare },
  { name: "Target", icon: Target },
  { name: "Flag", icon: Flag },
  { name: "Bookmark", icon: Bookmark },
  { name: "Tag", icon: Tag },
  { name: "Gauge", icon: Gauge },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "BarChart3", icon: BarChart3 },
  { name: "LineChart", icon: LineChart },
  { name: "PieChart", icon: PieChart },
  { name: "Activity", icon: Activity },
  { name: "Percent", icon: Percent },

  // Rewards
  { name: "Star", icon: Star },
  { name: "Award", icon: Award },
  { name: "Trophy", icon: Trophy },
  { name: "Medal", icon: Medal },
  { name: "Crown", icon: Crown },
  { name: "Sparkles", icon: Sparkles },
  { name: "Zap", icon: Zap },
  { name: "Rocket", icon: Rocket },

  // Making and listening
  { name: "Music", icon: Music },
  { name: "Headphones", icon: Headphones },
  { name: "Mic", icon: Mic },
  { name: "Video", icon: Video },
  { name: "Film", icon: Film },
  { name: "Camera", icon: Camera },
  { name: "Image", icon: Image },
  { name: "Palette", icon: Palette },
  { name: "Gamepad2", icon: Gamepad2 },

  // Body and rest
  { name: "Dumbbell", icon: Dumbbell },
  { name: "HeartPulse", icon: HeartPulse },
  { name: "Heart", icon: Heart },
  { name: "Bed", icon: Bed },
  { name: "Coffee", icon: Coffee },
  { name: "Utensils", icon: Utensils },
  { name: "Apple", icon: Apple },
  { name: "Leaf", icon: Leaf },
  { name: "TreePine", icon: TreePine },
  { name: "Feather", icon: Feather },
  { name: "Smile", icon: Smile },

  // Places and people
  { name: "Home", icon: Home },
  { name: "Building2", icon: Building2 },
  { name: "Briefcase", icon: Briefcase },
  { name: "Users", icon: Users },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "Mail", icon: Mail },
  { name: "Phone", icon: Phone },
  { name: "Wallet", icon: Wallet },
  { name: "Key", icon: Key },
  { name: "Lock", icon: Lock },
  { name: "Shield", icon: Shield },
]

export const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map((o) => [o.name, o.icon]),
)

export const FALLBACK_ICON = HelpCircle
